process.env.tedious_userName="shaharamit"
process.env.tedious_password="qazwsX11"
process.env.tedious_server="soccerserver2.database.windows.net"
process.env.tedious_database="soccerDB"
process.env.COOKIE_SECRET="ex32cookies"
process.env.api_token="AK7BhFnMhZxoDHXoUooIGcO7wtCD5x8Fyvb6hL2BnYTu8C9MmZd4VI2u20AN"
process.env.bcrypt_saltRounds="13"
process.env.PORT="3001"