process.env.tedious_userName="shaharamit"
process.env.tedious_password="qazwsX11"
process.env.tedious_server="soccerserver2.database.windows.net"
process.env.tedious_database="soccerDB"
process.env.COOKIE_SECRET="ex32cookies"
process.env.api_token="BIJy1elnJURAkyIEqj8ZGb8fTX9ppKHQBFXWggRHXxuXQwxdkIc66ahsCXk3"
process.env.bcrypt_saltRounds="13"