process.env.tedious_userName="shaharamit"
process.env.tedious_password="qazwsX11"
process.env.tedious_server="soccerserver2.database.windows.net"
process.env.tedious_database="soccerDB"
process.env.COOKIE_SECRET="ex32cookies"
process.env.api_token="wyaSGK1Im2jIkvT56YgKM2Ykp5GzmkBKIqlSJHdsu9TFK9vaBqvTR3HGuxPB"
process.env.bcrypt_saltRounds="13"
process.env.PORT="3001"